spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carShop
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      pool-name: SpringHickariPool
    jpa:
      hibernate:
        use-new-id-generator-mapping: true
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
